name: Build and Push Docker Images

on:
  workflow_dispatch:
    branches:
      - mine

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: wongsyrone/iptv-api:full
          platforms: linux/amd64
          build-args: |
            APP_WORKDIR=/iptv-api
            LITE=False

      - name: Build and push Docker image (Lite)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: wongsyrone/iptv-api:lite
          platforms: linux/amd64
          build-args: |
            APP_WORKDIR=/iptv-api-lite
            LITE=True
